# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Internal VM
  config.vm.define "Internal" do |internal|
    internal.vm.box = "bento/ubuntu-20.04"
    internal.vm.hostname = "Internal"

    # Internal network interface
    internal.vm.network "private_network", ip: "172.10.0.10", virtualbox__intnet: "internal_network"
  
    internal.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end

    # Provisioning script
    internal.vm.provision "shell", path: "provision/Internal.sh" if File.exist?("provision/Internal.sh")
  end


  # External VM
  config.vm.define "Attacker" do |attacker|
    attacker.vm.box = "bento/debian-11"
    attacker.vm.hostname = "Attacker"

    # network interface
    attacker.vm.network "private_network", ip: "192.168.60.11", virtualbox__intnet: "External_network"

    attacker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end

    # Provisioning script
    attacker.vm.provision "shell", path: "provision/Attacker.sh" if File.exist?("provision/Attacker.sh")
    
  end

  # Router VM
  config.vm.define "Router" do |router|
    router.vm.box = "bento/debian-11"
    router.vm.hostname = "Router"

    # External network interface (host-only)
    router.vm.network "private_network", ip: "192.168.60.253", virtualbox__intnet: "External_network"

    # Internal network interface
    router.vm.network "private_network", ip: "172.10.0.254", virtualbox__intnet: "internal_network"


    # Shared folder
    router.vm.synced_folder ".", "/vagrant"

    router.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Adjust this value (in MB) as needed
      vb.cpus = 1
    end

    # Provisioning script
    router.vm.provision "shell", path: "provision/Router.sh" if File.exist?("provision/Router.sh")
  end
end
